### ISSUE TITLE
Обновление/удаление пакетов под Bootstrap 3

### ISSUE THREAD

**Issue by alxlapin** [pozitronik/bc#1]
С цельюю перехода на Bootstrap 4 необходимо модифицировать следующие пакеты, т. к. в зависимостях указан Bootstrap 3:
pozitronik/yii2-navigationwidget
pozitronik/yii2-grid-config
2amigos/yii2-multi-select-widget - если планируется использование этого виджета, то в базовом проекте предлагаю оставить, а в PRPL удалим

**Comment by pozitronik** [comment]
yii2-references: выпилена зависимость от yii2-navigationwidget.
yii2-grid-config: выпилена зависимость от bootstrap.

На 2amigos/yii2-multi-select-widget завязан редактор групп доступов, и ничего удобнее я не знаю:
![изображение](https://user-images.githubusercontent.com/2357892/117846821-75695380-b28a-11eb-99b8-329ad7104956.png)
предложишь альтернативу?
